services:
  - type: web
    name: cover-letter-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - backend/**/*
